package rules;

import java.util.*;
import java.math.BigDecimal;

import com.maycur.sdk.rule.domain.*;
import com.maycur.sdk.rule.domain.result.*;
import com.maycur.sdk.rule.service.*;
import org.joda.time.Days;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.slf4j.Logger;

global AllowanceService allowanceService;
global Logger logger;

dialect  "mvel"

/*
	判断日期是否半天或重叠
    @param map 存入多个用户的行程日期集合
    @param userCode 内部员工编码
    @param day 行程某天的日期
    @param startDate 行程出发日期
    @param endDate 行程返回日期
    @param hourPoint 时间点
    @return -1表示重叠,0表示半天,1表示全天
 */
function int isDayHalveOrOverlap(Map map, String userCode, DateTime day, DateTime startDate, DateTime endDate, int hourPoint) {
    // 存储日期列表
    List days = null;
    // 判断当前用户是否存有日期列表
    if(map.get(userCode) == null) {
        days = new ArrayList();
    } else {
        days = (List)map.get(userCode);
    }
    // 设置上午时间
    String amDay = day.toString("yyyy-MM-dd") + "am";
    // 设置下午时间
	String pmDay = day.toString("yyyy-MM-dd") + "pm";
    // 判断是否是行程的出发时间
	if(day.withTimeAtStartOfDay().isEqual(startDate.withTimeAtStartOfDay())) {
		// 出发时间在12点后(含)，当天为半天
		if(startDate.getHourOfDay() >= hourPoint) {
			// 判断下午的日期是否存在于日期列表中
            if(days.contains(pmDay)) {
            	return -1;
            }
            days.add(pmDay);
            map.put(userCode, days);
			return 0;
		}
	}
    // 判断是否是行程的返回时间
    if(day.withTimeAtStartOfDay().isEqual(endDate.withTimeAtStartOfDay())) {
		// 返回时间12点前，当天为半天
		if(endDate.getHourOfDay() < hourPoint || (endDate.getHourOfDay() == hourPoint && endDate.getMinuteOfHour() == 0)) {
			// 判断上午的日期是否存在于日期列表中
            if(days.contains(amDay)) {
            	return -1;
            }
            days.add(amDay);
            map.put(userCode, days);
			return 0;
		}
	}
    // 标识符
    int flag = 1;
    // 判断上午的日期是否存在于日期列表中
    if(days.contains(amDay)) {
        flag = flag - 1;
    } else {
        days.add(amDay);
    }
    // 判断下午的日期是否存在于日期列表中
    if(days.contains(pmDay)) {
        flag = flag - 1;
    } else {
        days.add(pmDay);
    }
	map.put(userCode, days);
    return flag;
}

// 创建全局参数
declare TravelHalfDayKeys
	dateMap : Map // 存储日期集合
    name: String // 公司账套名称
	bizCodeOne : String // 标准补贴编码一
	feeCodeOne : String // 费用类型编码一
    hourPointOne : Integer // 费用类型编码一
end

rule "初始化参数"
    salience 30
    when
        // 判断是否有单据
        Reimburse();
    then
        String name = "xxx公司"; // 设置公司账套名称(方便查询日志)
		String bizCodeOne = "footAllowance"; // 设置标准补贴编码一
		String feeCodeOne = "BT"; // 设置返回费用类型编码一
        Integer hourPointOne = 12; // 设置判断标准一半天的时间点

        insert(new TravelHalfDayKeys(new HashMap(), name, bizCodeOne, feeCodeOne, hourPointOne));
end

rule "报销人和参与人费用标准一规则计算"
    salience 20
    when
        // 获取变量参数
        TravelHalfDayKeys(
            $dateMap:dateMap, // 获取日期集合
            $name:name, // 获取公司账套名称
            $bizCodeOne:bizCodeOne, // 获取准补贴编码一
            $feeCodeOne:feeCodeOne, // 获取费用类型编码一
            $hourPointOne:hourPointOne // 获取判断标准一半天的时间点
        );
        // 获取单据
        Reimburse(
            $travelRoutes:travelRoutes, // 行程信息
            $reimEmployee:reimEmployee, // 报销人信息
            $collectionCcy:collectionCcy, // 收款币种
            $baseCcy:baseCcy // 本币
        );
        // 获取行程信息
        $travelRecord : TravelRoute(
            $startDate:startDate, // 行程出发时间
            $endDate:endDate, // 行程返回时间
            $destination:destination, // 行程目的地
            $allowanceStandardInfos:allowanceStandardInfos, // 报销人补贴标准信息
            $travelPartnerInfo:travelPartnerInfo, // 参与人信息
            $partnerAllowanceStandardInfos:partnerAllowanceStandardInfos // 参与人补贴标准信息
        ) from $travelRoutes;
        // 获取补贴信息
		$allowanceStandardInfo : AllowanceStandardInfo(
			$bizCodeOne.equals(ruleBizCode) // 补贴标准编码
		) from $allowanceStandardInfos;
    then
        /**设置补贴总金额 */
		BigDecimal amount = BigDecimal.ZERO;

        /**获取根据行程的开始结束时间计算出差天数**/
        List dateTimes = allowanceService.getTripDiffDays($travelRecord);

        /**循环出差天数 */
        for(Object obj : dateTimes) {
            
            /**转换成日期对象 */
            DateTime dateTime = (DateTime)obj;

           

            /**====== 计算参与人补贴金额 ======*/
            /**判断是否有参与人 */
            if($travelPartnerInfo != null) {

                /**循环参与人信息列表 */
                for(TravelPartner travelPartner : $travelPartnerInfo.getInternalTravelPartner) {

                    /**获取补贴标准金额 */
                    BigDecimal partnerAllowanceAmount = allowanceService.getDestinationPartnerAllowanceStandard(
                        dateTime,
                        $partnerAllowanceStandardInfos,
                        travelPartner,
                        $bizCodeOne
                    );

                    /** 获取行程中的时间是否有半天或重叠 */
                    int state = isDayHalveOrOverlap(
                        $dateMap, 
                        travelPartner.getUserCode() + "ONE", 
                        dateTime, 
                        $startDate, 
                        $endDate,
                        $hourPointOne
                    );

                    logger.info($name + "补贴标准一参与人行程日期为" + dateTime +",补贴参与人编号为" + travelPartner.getUserCode() + ",补贴日期判断状态为" + state);

                    /** 判断是否为全天 */
                    if(state == 1) {

                        amount = amount.add(partnerAllowanceAmount);

                    /** 判断是否为半天 */
                    } else if (state == 0) {

                        amount = amount.add(partnerAllowanceAmount.divide(BigDecimal.valueOf(2)));
                    

                    }

                }

            }

        }

        /**判断出差补助是否大于零 */
        if(amount.compareTo(BigDecimal.ZERO) == 1) {

            /** 获取目的地城市币种 */
            String ccy = allowanceService.getDestinationAllowanceStandardCcy($endDate, $allowanceStandardInfo);

            /**返回补贴结果 */
            AllowanceResult allowanceResult = new AllowanceResult($startDate, $feeCodeOne, amount, ccy, ccy);
            /**设置消费城市 */
            allowanceResult.setConsumeLocation($destination);

            insert(allowanceResult);
        }
end
