package rules;

import java.util.*;
import java.math.BigDecimal;

import com.maycur.sdk.rule.domain.*;
import com.maycur.sdk.rule.domain.result.*;
import com.maycur.sdk.rule.service.*;
import org.joda.time.Days;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.slf4j.Logger;

global AllowanceService allowanceService;
global Logger logger;

dialect  "mvel"

/*
	判断日期是否半天或重叠
    @param map 存入多个用户的行程日期集合
    @param userCode 内部员工编码
    @param day 行程某天的日期
    @param startDate 行程出发日期
    @param endDate 行程返回日期
    @return -1表示重叠,0表示半天,1表示全天
 */
function int isDayHalveOrOverlap(Map map, String userCode, DateTime day, DateTime startDate, DateTime endDate) {
    // 标识符
    int flag = 1;
    // 存储日期列表
    List days = null;
    // 判断当前用户是否存有日期列表
    if(map.get(userCode) == null) {
        days = new ArrayList();
    } else {
        days = (List)map.get(userCode);
    }
    // 设置上午时间
    String amDay = day.toString("yyyy-MM-dd") + "am";
    // 设置下午时间
	String pmDay = day.toString("yyyy-MM-dd") + "pm";
    // 判断是否是行程的出发时间
	if(day.getYear() == startDate.getYear() 
		&& day.getMonthOfYear() == startDate.getMonthOfYear() 
		&& day.getDayOfMonth() == startDate.getDayOfMonth()) {
		// 出发时间在12点后(含)，当天为半天
		if(startDate.getHourOfDay() >= 12) {
			// 判断下午的日期是否存在于日期列表中
            if(days.contains(pmDay)) {
            	return -1;
            }
            days.add(pmDay);
            map.put(userCode, days);
			return 0;
		}
	}
    // 判断是否是行程的返回时间
    if(day.getYear() == endDate.getYear() 
		&& day.getMonthOfYear() == endDate.getMonthOfYear() 
		&& day.getDayOfMonth() == endDate.getDayOfMonth()) {
		// 返回时间12点前，当天为半天
		if(endDate.getHourOfDay() < 12) {
			// 判断上午的日期是否存在于日期列表中
            if(days.contains(amDay)) {
            	return -1;
            }
            days.add(amDay);
            map.put(userCode, days);
			return 0;
		// 返回时间(含)12点，当天为半天
		} else if (endDate.getHourOfDay() == 12 
			&& endDate.getMinuteOfHour() == 0) {
			// 判断上午的日期是否存在于日期列表中
            if(days.contains(amDay)) {
            	return -1;
            }
            days.add(amDay);
            map.put(userCode, days);
			return 0;
		}
	}
    // 判断上午和下午是否在日期列表中
    if(days.contains(amDay) && days.contains(pmDay)) {
        return -1;
    } else {
        // 判断上午的日期是否存在于日期列表中
        if(days.contains(amDay)) {
            flag = 0;
        } else {
            days.add(amDay);
        }
        // 判断下午的日期是否存在于日期列表中
        if(days.contains(pmDay)) {
                flag = 0;
        } else {
            days.add(pmDay);
        }
    }
	map.put(userCode, days);
    return flag;
}

// 创建全局参数
declare TravelHalfDayKeys
	dateMap : Map // 存储日期集合
	firstBizCode : String // 第一个标准补贴编码
	firstFeeCode : String // 第一个费用类型编码
    secondBizCode: String // 第二个标准补贴编码
    secondFeeCode: String // 第二个费用类型编码
end

rule "初始化参数"
    salience 30
    when
        Reimburse(); // 判断是否有单据
    then
		String firstBizCode = "footAllowance"; // 设置第一个标准补贴编码
		String firstFeeCode = "12345"; // 设置第一个费用类型编码
        String secondBizCode = "test123"; // 设置第二个标准补贴编码
        String secondFeeCode = "1014"; // 设置第二个费用类型编码
        insert(new TravelHalfDayKeys(new HashMap(), firstBizCode, firstFeeCode,secondBizCode,secondFeeCode));
end

rule "报销人费用规则计算"
    salience 20
   when
        // 获取变量参数
        TravelHalfDayKeys(
            $dateMap:dateMap, // 获取日期集合
            $firstBizCode:firstBizCode, // 获取准补贴编码
            $firstFeeCode:firstFeeCode // 获取费用类型编码
        );
        // 获取单据
        Reimburse(
            $travelRoutes:travelRoutes, // 行程信息
            $reimEmployee:reimEmployee, // 报销人信息
            $collectionCcy:collectionCcy, // 收款币种
            $baseCcy:baseCcy // 本币
        );
        // 判断是否有报销人信息
        eval($reimEmployee != null);
        // 获取行程信息
        $travelRecord : TravelRoute(
            $startDate:startDate, // 行程出发时间
            $endDate:endDate, // 行程返回时间
            $destination:destination, // 行程目的地
            $allowanceStandardInfos:allowanceStandardInfos // 报销人补贴标准信息
        ) from $travelRoutes;
        // 根据行程的开始结束时间计算出差天数
        $dateTime : DateTime() from allowanceService.getTripDiffDays($travelRecord);
        // 获取补贴信息
		$allowanceStandardInfo : AllowanceStandardInfo(
			$firstBizCode.equals(ruleBizCode) // 补贴标准编码
		) from $allowanceStandardInfos;
    then

        // 获取报销人补贴金额，根据日期获取对应的目的地补贴标准
        BigDecimal allowanceAmount = allowanceService.getDestinationAllowanceStandard(
           $dateTime, 
           $allowanceStandardInfo
        );

        // 获取行程中的时间是否有半天或重叠
        int state = isDayHalveOrOverlap(
            $dateMap, 
            $reimEmployee.getUserCode()+1, 
            $dateTime, 
            $startDate, 
            $endDate
        );

        logger.info("补贴测试行程日期为" + $dateTime +",补贴测试报销人编号为" + $reimEmployee.getUserCode() + ",补贴测试日期判断状态为" + state);

        if(state == 1) {
            insert(new AllowanceResult(
                $dateTime, 
                $firstFeeCode, 
                allowanceAmount,
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        } else if (state == 0) {
            insert(new AllowanceResult(
                $dateTime, 
                $firstFeeCode, 
                allowanceAmount.divide(BigDecimal.valueOf(2)),
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        }
end

rule "行程参与人费用规则计算"
    salience 10
    when
        // 获取变量参数
        TravelHalfDayKeys(
            $dateMap:dateMap, // 获取日期集合
            $firstBizCode:firstBizCode, // 获取准补贴编码
            $firstFeeCode:firstFeeCode // 获取费用类型编码
        );
        // 获取单据
        Reimburse(
            $travelRoutes:travelRoutes, // 行程信息
            $collectionCcy:collectionCcy, // 收款币种
            $baseCcy:baseCcy // 本币
        );
        // 获取行程信息
        $travelRecord : TravelRoute(
            $startDate:startDate, // 行程出发时间
            $endDate:endDate, // 行程返回时间
            $destination:destination, // 行程目的地
            $travelPartnerInfo:travelPartnerInfo, // 参与人信息
            $partnerAllowanceStandardInfos:partnerAllowanceStandardInfos // 参与人补贴标准信息
        ) from $travelRoutes;
        // 判断是否有参与人
        eval($travelPartnerInfo != null);
        // 根据行程的开始结束时间计算出差天数
        $dateTime : DateTime() from allowanceService.getTripDiffDays($travelRecord);
        // 获取内部同行人
        $travelPartner : TravelPartner() from $travelPartnerInfo.getInternalTravelPartner();
    then

        // 获取参与人补贴金额
        BigDecimal partnerAllowanceAmount = allowanceService.getDestinationPartnerAllowanceStandard(
            $dateTime,
            $partnerAllowanceStandardInfos,
            $travelPartner,
            $firstBizCode
        );

        // 获取行程中的时间是否有半天或重叠
        int state = isDayHalveOrOverlap(
            $dateMap, 
            $travelPartner.getUserCode()+1, 
            $dateTime, 
            $startDate, 
            $endDate
        );

        logger.info("补贴测试行程日期为" + $dateTime +",补贴测试参与人编号为" + $travelPartner.getUserCode() + ",补贴测试日期判断状态为" + state);

        if(state == 1) {
            insert(new AllowanceResult(
                $dateTime, 
                $firstFeeCode, 
                partnerAllowanceAmount,
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        } else if (state == 0) {
            insert(new AllowanceResult(
                $dateTime, 
                $firstFeeCode, 
                partnerAllowanceAmount.divide(BigDecimal.valueOf(2)),
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        }
end




rule "报销人费用规则计算2"
    salience 20
   when
        // 获取变量参数
        TravelHalfDayKeys(
            $dateMap:dateMap, // 获取日期集合
            $secondBizCode:secondBizCode, // 获取准补贴编码
            $secondFeeCode:secondFeeCode // 获取费用类型编码
        );
        // 获取单据
        Reimburse(
            $travelRoutes:travelRoutes, // 行程信息
            $reimEmployee:reimEmployee, // 报销人信息
            $collectionCcy:collectionCcy, // 收款币种
            $baseCcy:baseCcy // 本币
        );
        // 判断是否有报销人信息
        eval($reimEmployee != null);
        // 获取行程信息
        $travelRecord : TravelRoute(
            $startDate:startDate, // 行程出发时间
            $endDate:endDate, // 行程返回时间
            $destination:destination, // 行程目的地
            $allowanceStandardInfos:allowanceStandardInfos // 报销人补贴标准信息
        ) from $travelRoutes;
        // 根据行程的开始结束时间计算出差天数
        $dateTime : DateTime() from allowanceService.getTripDiffDays($travelRecord);
        // 获取补贴信息
		$allowanceStandardInfo : AllowanceStandardInfo(
			$secondBizCode.equals(ruleBizCode) // 补贴标准编码
		) from $allowanceStandardInfos;
    then

        // 获取报销人补贴金额
        BigDecimal allowanceAmount = allowanceService.getDestinationAllowanceStandard(
           $dateTime, 
           $allowanceStandardInfo
        );

        // 获取行程中的时间是否有半天或重叠
        int state = isDayHalveOrOverlap(
            $dateMap, 
            $reimEmployee.getUserCode()+2, 
            $dateTime, 
            $startDate, 
            $endDate
        );

        logger.info("补贴测试行程日期为" + $dateTime +",补贴测试报销人编号为" + $reimEmployee.getUserCode() + ",补贴测试日期判断状态为" + state);

        if(state == 1) {
            insert(new AllowanceResult(
                $dateTime, 
                $secondFeeCode, 
                allowanceAmount,
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        } else if (state == 0) {
            insert(new AllowanceResult(
                $dateTime, 
                $secondFeeCode, 
                allowanceAmount.divide(BigDecimal.valueOf(2)),
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        }
end

rule "行程参与人费用规则计算2"
    salience 10
    when
        // 获取变量参数
        TravelHalfDayKeys(
            $dateMap:dateMap, // 获取日期集合
            $secondBizCode:secondBizCode, // 获取准补贴编码
            $secondFeeCode:secondFeeCode // 获取费用类型编码
        );
        // 获取单据
        Reimburse(
            $travelRoutes:travelRoutes, // 行程信息
            $collectionCcy:collectionCcy, // 收款币种
            $baseCcy:baseCcy // 本币
        );
        // 获取行程信息
        $travelRecord : TravelRoute(
            $startDate:startDate, // 行程出发时间
            $endDate:endDate, // 行程返回时间
            $destination:destination, // 行程目的地
            $travelPartnerInfo:travelPartnerInfo, // 参与人信息
            $partnerAllowanceStandardInfos:partnerAllowanceStandardInfos // 参与人补贴标准信息
        ) from $travelRoutes;
        // 判断是否有参与人
        eval($travelPartnerInfo != null);
        // 根据行程的开始结束时间计算出差天数
        $dateTime : DateTime() from allowanceService.getTripDiffDays($travelRecord);
        // 获取内部同行人
        $travelPartner : TravelPartner() from $travelPartnerInfo.getInternalTravelPartner();
    then

        // 获取参与人补贴金额
        BigDecimal partnerAllowanceAmount = allowanceService.getDestinationPartnerAllowanceStandard(
            $dateTime,
            $partnerAllowanceStandardInfos,
            $travelPartner,
            $secondBizCode
        );

        // 获取行程中的时间是否有半天或重叠
        int state = isDayHalveOrOverlap(
            $dateMap, 
            $travelPartner.getUserCode()+2, 
            $dateTime, 
            $startDate, 
            $endDate
        );

        logger.info("补贴测试行程日期为" + $dateTime +",补贴测试参与人编号为" + $travelPartner.getUserCode() + ",补贴测试日期判断状态为" + state);

        if(state == 1) {
            insert(new AllowanceResult(
                $dateTime, 
                $secondFeeCode, 
                partnerAllowanceAmount,
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        } else if (state == 0) {
            insert(new AllowanceResult(
                $dateTime, 
                $secondFeeCode, 
                partnerAllowanceAmount.divide(BigDecimal.valueOf(2)),
                $baseCcy, 
                $collectionCcy, 
                $destination
            ));
        }
end